export const FEATURED_GAMES = [
  {
    id: 'game_0',
    title: 'Super Mario Bros.',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Super%20Mario%20Bros.%20%28World%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Mario%20Bros.%20%28World%29.png',
  },
  {
    id: 'game_1',
    title: 'Super Mario Bros. 2',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Super%20Mario%20Bros.%202%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Mario%20Bros.%202%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_2',
    title: 'Super Mario Bros. 3',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Super%20Mario%20Bros.%203%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Mario%20Bros.%203%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_3',
    title: 'The Legend of Zelda',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Legend%20of%20Zelda%2C%20The%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Legend%20of%20Zelda%2C%20The%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_4',
    title: 'Contra',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Contra%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Contra%20%28USA%29.png',
  },
  {
    id: 'game_5',
    title: 'Mega Man 2',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Mega%20Man%202%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Mega%20Man%202%20%28USA%29.png',
  },
  {
    id: 'game_6',
    title: 'Mega Man 3',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Mega%20Man%203%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Mega%20Man%203%20%28USA%29.png',
  },
  {
    id: 'game_7',
    title: 'Castlevania',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Castlevania%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Castlevania%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_8',
    title: 'Castlevania III',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Castlevania%20III%20-%20Draculas%20Curse%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Castlevania%20III%20-%20Draculas%20Curse%20%28USA%29.png',
  },
  {
    id: 'game_9',
    title: 'Metroid',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Metroid%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Metroid%20%28USA%29.png',
  },
  {
    id: 'game_10',
    title: 'Mike Tysons Punch-Out!!',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Mike%20Tysons%20Punch-Out%21%21%20%28Japan%2C%20USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Mike%20Tysons%20Punch-Out%21%21%20%28Japan%2C%20USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_11',
    title: 'DuckTales',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/DuckTales%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/DuckTales%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_12',
    title: 'Ninja Gaiden',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Ninja%20Gaiden%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Ninja%20Gaiden%20%28USA%29.png',
  },
  {
    id: 'game_13',
    title: 'Ninja Gaiden II',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Ninja%20Gaiden%20II%20-%20The%20Dark%20Sword%20of%20Chaos%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Ninja%20Gaiden%20II%20-%20The%20Dark%20Sword%20of%20Chaos%20%28USA%29.png',
  },
  {
    id: 'game_14',
    title: 'Tetris',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Tetris%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Tetris%20%28USA%29.png',
  },
  {
    id: 'game_15',
    title: 'Final Fantasy',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Final%20Fantasy%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Final%20Fantasy%20%28USA%29.png',
  },
  {
    id: 'game_16',
    title: 'Kirbys Adventure',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Kirbys%20Adventure%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Kirbys%20Adventure%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_17',
    title: 'Double Dragon',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Double%20Dragon%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Double%20Dragon%20%28USA%29.png',
  },
  {
    id: 'game_18',
    title: 'Double Dragon II',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Double%20Dragon%20II%20-%20The%20Revenge%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Double%20Dragon%20II%20-%20The%20Revenge%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_19',
    title: 'Battletoads',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Battletoads%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Battletoads%20%28USA%29.png',
  },
  {
    id: 'game_20',
    title: 'Excitebike',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Excitebike%20%28Japan%2C%20USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Excitebike%20%28Japan%2C%20USA%29.png',
  },
  {
    id: 'game_21',
    title: 'TMNT',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Teenage%20Mutant%20Ninja%20Turtles%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Teenage%20Mutant%20Ninja%20Turtles%20%28USA%29.png',
  },
  {
    id: 'game_22',
    title: 'TMNT II',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Teenage%20Mutant%20Ninja%20Turtles%20II%20-%20The%20Arcade%20Game%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Teenage%20Mutant%20Ninja%20Turtles%20II%20-%20The%20Arcade%20Game%20%28USA%29.png',
  },
  {
    id: 'game_23',
    title: 'Bionic Commando',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Bionic%20Commando%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Bionic%20Commando%20%28USA%29.png',
  },
  {
    id: 'game_24',
    title: 'Blaster Master',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Blaster%20Master%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Blaster%20Master%20%28USA%29.png',
  },
  {
    id: 'game_25',
    title: 'Zelda II',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Zelda%20II%20-%20The%20Adventure%20of%20Link%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Zelda%20II%20-%20The%20Adventure%20of%20Link%20%28USA%29.png',
  },
  {
    id: 'game_26',
    title: 'Dr. Mario',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Dr.%20Mario%20%28Japan%2C%20USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Dr.%20Mario%20%28Japan%2C%20USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_27',
    title: 'Pac-Man',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Pac-Man%20%28USA%29%20%28Namco%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Pac-Man%20%28USA%29%20%28Namco%29.png',
  },
  {
    id: 'game_28',
    title: 'Super C',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Super%20C%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20C%20%28USA%29.png',
  },
  {
    id: 'game_29',
    title: 'Life Force',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Life%20Force%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Life%20Force%20%28USA%29.png',
  },
  {
    id: 'game_30',
    title: 'Gradius',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Gradius%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Gradius%20%28USA%29.png',
  },
  {
    id: 'game_31',
    title: 'Ghostsn Goblins',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Ghostsn%20Goblins%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Ghostsn%20Goblins%20%28USA%29.png',
  },
  {
    id: 'game_32',
    title: 'Ice Climber',
    system: 'nes',
    romUrl: 'https://cors.archive.org/cors/No-Intro_NES/Ice%20Climber%20%28USA%2C%20Europe%2C%20Korea%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Ice%20Climber%20%28USA%2C%20Europe%2C%20Korea%29.png',
  },
  {
    id: 'game_33',
    title: 'Super Mario World',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Super%20Mario%20World%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Mario%20World%20%28USA%29.png',
  },
  {
    id: 'game_34',
    title: 'Super Metroid',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Super%20Metroid%20%28Japan%2C%20USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Metroid%20%28Japan%2C%20USA%29.png',
  },
  {
    id: 'game_35',
    title: 'Zelda: A Link to the Past',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Legend%20of%20Zelda%2C%20The%20-%20A%20Link%20to%20the%20Past%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Legend%20of%20Zelda%2C%20The%20-%20A%20Link%20to%20the%20Past%20%28USA%29.png',
  },
  {
    id: 'game_36',
    title: 'Chrono Trigger',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Chrono%20Trigger%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Chrono%20Trigger%20%28USA%29.png',
  },
  {
    id: 'game_37',
    title: 'Super Mario Kart',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Super%20Mario%20Kart%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Mario%20Kart%20%28USA%29.png',
  },
  {
    id: 'game_38',
    title: 'Donkey Kong Country',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Donkey%20Kong%20Country%20%28USA%29%20%28Rev%202%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Donkey%20Kong%20Country%20%28USA%29%20%28Rev%202%29.png',
  },
  {
    id: 'game_39',
    title: 'Donkey Kong Country 2',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Donkey%20Kong%20Country%202%20-%20Diddy%27s%20Kong%20Quest%20%28USA%29%20%28En%2CFr%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Donkey%20Kong%20Country%202%20-%20Diddys%20Kong%20Quest%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_40',
    title: 'Donkey Kong Country 3',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Donkey%20Kong%20Country%203%20-%20Dixie%20Kong%27s%20Double%20Trouble%21%20%28USA%29%20%28En%2CFr%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Donkey%20Kong%20Country%203%20-%20Dixie%20Kongs%20Double%20Trouble%21%20%28USA%29.png',
  },
  {
    id: 'game_41',
    title: 'EarthBound',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/EarthBound%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/EarthBound%20%28USA%29.png',
  },
  {
    id: 'game_42',
    title: 'Final Fantasy III (VI)',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Final%20Fantasy%20III%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Final%20Fantasy%20III%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_43',
    title: 'Final Fantasy II (IV)',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Final%20Fantasy%20II%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Final%20Fantasy%20II%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_44',
    title: 'Super Mario RPG',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Super%20Mario%20RPG%20-%20Legend%20of%20the%20Seven%20Stars%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Mario%20RPG%20-%20Legend%20of%20the%20Seven%20Stars%20%28USA%29.png',
  },
  {
    id: 'game_45',
    title: 'Mega Man X',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Mega%20Man%20X%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Mega%20Man%20X%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_46',
    title: 'Street Fighter II Turbo',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Street%20Fighter%20II%20Turbo%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Street%20Fighter%20II%20Turbo%20%28USA%29.png',
  },
  {
    id: 'game_47',
    title: 'Super Street Fighter II',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Super%20Street%20Fighter%20II%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Street%20Fighter%20II%20%28USA%29.png',
  },
  {
    id: 'game_48',
    title: 'Star Fox',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Star%20Fox%20%28USA%29%20%28Rev%202%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Star%20Fox%20%28USA%29%20%28Rev%202%29.png',
  },
  {
    id: 'game_49',
    title: 'F-Zero',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/F-Zero%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/F-Zero%20%28USA%29.png',
  },
  {
    id: 'game_50',
    title: 'Secret of Mana',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Secret%20of%20Mana%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Secret%20of%20Mana%20%28USA%29.png',
  },
  {
    id: 'game_51',
    title: 'Super Castlevania IV',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Super%20Castlevania%20IV%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Castlevania%20IV%20%28USA%29.png',
  },
  {
    id: 'game_52',
    title: 'Contra III',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Contra%20III%20-%20The%20Alien%20Wars%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Contra%20III%20-%20The%20Alien%20Wars%20%28USA%29.png',
  },
  {
    id: 'game_53',
    title: 'TMNT IV: Turtles in Time',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Turtles%20in%20Time%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Turtles%20in%20Time%20%28USA%29.png',
  },
  {
    id: 'game_54',
    title: 'Super Mario World 2: Yoshis Island',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Yoshis%20Island%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Yoshis%20Island%20%28USA%29.png',
  },
  {
    id: 'game_55',
    title: 'Aladdin (SNES)',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Aladdin%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Aladdin%20%28USA%29.png',
  },
  {
    id: 'game_56',
    title: 'The Lion King',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Lion%20King%2C%20The%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Lion%20King%2C%20The%20%28USA%29.png',
  },
  {
    id: 'game_57',
    title: 'Mortal Kombat II',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Mortal%20Kombat%20II%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Mortal%20Kombat%20II%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_58',
    title: 'Ultimate Mortal Kombat 3',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Ultimate%20Mortal%20Kombat%203%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Ultimate%20Mortal%20Kombat%203%20%28USA%29.png',
  },
  {
    id: 'game_59',
    title: 'NBA Jam TE',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/NBA%20Jam%20-%20Tournament%20Edition%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/NBA%20Jam%20-%20Tournament%20Edition%20%28USA%29.png',
  },
  {
    id: 'game_60',
    title: 'Killer Instinct',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Killer%20Instinct%20%28USA%29%20%28Rev%201%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Killer%20Instinct%20%28USA%29%20%28Rev%201%29.png',
  },
  {
    id: 'game_61',
    title: 'Zombies Ate My Neighbors',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Zombies%20Ate%20My%20Neighbors%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Zombies%20Ate%20My%20Neighbors%20%28USA%29.png',
  },
  {
    id: 'game_62',
    title: 'Earthworm Jim',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Earthworm%20Jim%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Earthworm%20Jim%20%28USA%29.png',
  },
  {
    id: 'game_63',
    title: 'Super Punch-Out!!',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Super%20Punch-Out%21%21%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Punch-Out%21%21%20%28USA%29.png',
  },
  {
    id: 'game_64',
    title: 'SimCity',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/SimCity%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/SimCity%20%28USA%29.png',
  },
  {
    id: 'game_65',
    title: 'Harvest Moon',
    system: 'snes',
    romUrl: 'https://cors.archive.org/cors/ef_nintendo_snes_no-intro_2024-04-20/Harvest%20Moon%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Harvest%20Moon%20%28USA%29.png',
  },
  {
    id: 'game_66',
    title: 'Sonic The Hedgehog',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Sonic%20The%20Hedgehog%20%28USA%2C%20Europe%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Sonic%20The%20Hedgehog%20%28USA%2C%20Europe%29.png',
  },
  {
    id: 'game_67',
    title: 'Sonic The Hedgehog 2',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Sonic%20The%20Hedgehog%202%20%28World%29%20%28Rev%20A%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Sonic%20The%20Hedgehog%202%20%28World%29%20%28Rev%20A%29.png',
  },
  {
    id: 'game_68',
    title: 'Sonic The Hedgehog 3',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Sonic%20The%20Hedgehog%203%20%28USA%29%20%28En%2CJa%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Sonic%20The%20Hedgehog%203%20%28USA%29%20%28En%2CJa%29.png',
  },
  {
    id: 'game_69',
    title: 'Sonic & Knuckles',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Sonic%20%26%20Knuckles%20%28World%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Sonic%20%26%20Knuckles%20%28World%29.png',
  },
  {
    id: 'game_70',
    title: 'Streets of Rage 2',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Streets%20of%20Rage%202%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Streets%20of%20Rage%202%20%28USA%29.png',
  },
  {
    id: 'game_71',
    title: 'Streets of Rage 3',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Streets%20of%20Rage%203%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Streets%20of%20Rage%203%20%28USA%29.png',
  },
  {
    id: 'game_72',
    title: 'Streets of Rage',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Streets%20of%20Rage%20%28World%29%20%28Rev%20A%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Streets%20of%20Rage%20%28World%29%20%28Rev%20A%29.png',
  },
  {
    id: 'game_73',
    title: 'Golden Axe',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Golden%20Axe%20%28World%29%20%28Rev%20A%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Golden%20Axe%20%28World%29%20%28Rev%20A%29.png',
  },
  {
    id: 'game_74',
    title: 'Golden Axe II',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Golden%20Axe%20II%20%28World%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Golden%20Axe%20II%20%28World%29.png',
  },
  {
    id: 'game_75',
    title: 'Disneys Aladdin',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Aladdin%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Aladdin%20%28USA%29.png',
  },
  {
    id: 'game_76',
    title: 'Earthworm Jim',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Earthworm%20Jim%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Earthworm%20Jim%20%28USA%29.png',
  },
  {
    id: 'game_77',
    title: 'Earthworm Jim 2',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Earthworm%20Jim%202%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Earthworm%20Jim%202%20%28USA%29.png',
  },
  {
    id: 'game_78',
    title: 'Mortal Kombat II',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Mortal%20Kombat%20II%20%28World%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Mortal%20Kombat%20II%20%28World%29.png',
  },
  {
    id: 'game_79',
    title: 'Mortal Kombat 3',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Mortal%20Kombat%203%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Mortal%20Kombat%203%20%28USA%29.png',
  },
  {
    id: 'game_80',
    title: 'Ultimate Mortal Kombat 3',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Ultimate%20Mortal%20Kombat%203%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Ultimate%20Mortal%20Kombat%203%20%28USA%29.png',
  },
  {
    id: 'game_81',
    title: 'Comix Zone',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Comix%20Zone%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Comix%20Zone%20%28USA%29.png',
  },
  {
    id: 'game_82',
    title: 'Contra: Hard Corps',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Contra%20-%20Hard%20Corps%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Contra%20-%20Hard%20Corps%20%28USA%29.png',
  },
  {
    id: 'game_83',
    title: 'Castlevania: Bloodlines',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Castlevania%20-%20Bloodlines%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Castlevania%20-%20Bloodlines%20%28USA%29.png',
  },
  {
    id: 'game_84',
    title: 'Gunstar Heroes',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Gunstar%20Heroes%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Gunstar%20Heroes%20%28USA%29.png',
  },
  {
    id: 'game_85',
    title: 'Phantasy Star IV',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Phantasy%20Star%20IV%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Phantasy%20Star%20IV%20%28USA%29.png',
  },
  {
    id: 'game_86',
    title: 'Shining Force II',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Shining%20Force%20II%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Shining%20Force%20II%20%28USA%29.png',
  },
  {
    id: 'game_87',
    title: 'Shinobi III',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Shinobi%20III%20-%20Return%20of%20the%20Ninja%20Master%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Shinobi%20III%20-%20Return%20of%20the%20Ninja%20Master%20%28USA%29.png',
  },
  {
    id: 'game_88',
    title: 'The Revenge of Shinobi',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Revenge%20of%20Shinobi%2C%20The%20%28USA%2C%20Europe%29%20%28Rev%20B%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Revenge%20of%20Shinobi%2C%20The%20%28USA%2C%20Europe%29%20%28Rev%20B%29.png',
  },
  {
    id: 'game_89',
    title: 'Vectorman',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Vectorman%20%28USA%2C%20Europe%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Vectorman%20%28USA%2C%20Europe%29.png',
  },
  {
    id: 'game_90',
    title: 'Vectorman 2',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Vectorman%202%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Vectorman%202%20%28USA%29.png',
  },
  {
    id: 'game_91',
    title: 'The Lion King',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Lion%20King%2C%20The%20%28World%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Lion%20King%2C%20The%20%28World%29.png',
  },
  {
    id: 'game_92',
    title: 'NBA Jam TE',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/NBA%20Jam%20-%20Tournament%20Edition%20%28World%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/NBA%20Jam%20-%20Tournament%20Edition%20%28World%29.png',
  },
  {
    id: 'game_93',
    title: 'Road Rash II',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Road%20Rash%20II%20%28USA%2C%20Europe%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Road%20Rash%20II%20%28USA%2C%20Europe%29.png',
  },
  {
    id: 'game_94',
    title: 'Micro Machines',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Micro%20Machines%20%28Europe%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Micro%20Machines%20%28Europe%29.png',
  },
  {
    id: 'game_95',
    title: 'Jungle Strike',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Jungle%20Strike%20%28USA%2C%20Europe%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Jungle%20Strike%20%28USA%2C%20Europe%29.png',
  },
  {
    id: 'game_96',
    title: 'Desert Strike',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Desert%20Strike%20-%20Return%20to%20the%20Gulf%20%28USA%2C%20Europe%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Desert%20Strike%20-%20Return%20to%20the%20Gulf%20%28USA%2C%20Europe%29.png',
  },
  {
    id: 'game_97',
    title: 'Urban Strike',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Urban%20Strike%20%28USA%2C%20Europe%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Urban%20Strike%20%28USA%2C%20Europe%29.png',
  },
  {
    id: 'game_98',
    title: 'ToeJam & Earl',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Toejam%20%26%20Earl%20%28World%29%20%28Rev%20A%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Toejam%20%26%20Earl%20%28World%29%20%28Rev%20A%29.png',
  },
  {
    id: 'game_99',
    title: 'ToeJam & Earl in Panic on Funkotron',
    system: 'segaMD',
    romUrl: 'https://cors.archive.org/cors/ef_mega_genesis_no-intro_2024-04-21/Toejam%20%26%20Earl%20in%20Panic%20on%20Funkotron%20%28USA%29.zip',
    coverUrl: 'https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Toejam%20%26%20Earl%20in%20Panic%20on%20Funkotron%20%28USA%29.png',
  },
];
